### ISSUE TITLE
Current progress

### ISSUE THREAD

**Issue by hartmark** [afwbkbc/glsmac#2]
This sounds like a nice project and will closely watch this progress as SMAC is one of my favourite games.

Can you please add some kind of outline of where you are in the development.

What works, what doesn't with perhaps tasks which are needed to get fixed before the feature is done.

Something like this for an outline:
https://github.com/OpenRA/OpenRA/wiki/Development-Goals

And something like this for a given feature:
https://github.com/OpenRA/OpenRA/issues/4988

I realize this is quite early in the development so having specific pages like OpenRA is perhaps a bit overkill. But in the long run I think it would be nice to split down into separate tasks where people have an easier way of grabbing something to write a PR for.

**Comment by afwbkbc** [comment]
For now I'm working on basic engine functions and started map rendering few days ago. What works - basically just menu, and multiplayer lobby to some extent (it's possible to join somebody's game and then leave, or host own game).
There is roadmap in README, and current version is v0.1 ( I'll add it there too when I commit next time ). I don't want to spend too much time on documentation right now, releasing somewhat playable game (version v0.4+) is higher priority for now.

**Comment by hartmark** [comment]
Fair enough, make sense to focus to get more stuff working this early in the developing.

Saw that there was some more info in discord too.

I haven't programmed c++ in years so I don't know how helpful I would be for writing new features, but I'd gladly spend time to test stuff.

Keep up the good work!
