### ISSUE TITLE
not create GLSMAC.exe VS22 Windows11

### ISSUE THREAD

**Issue by Komatozzz** [afwbkbc/glsmac#28]
Hi
On steps "Once that is done you should clone the git, then open the folder. Press the top button **Project**->**Configure**, then the output should open. Wait for it to say "CMake generation finished.". Once that is done select the build target `GLSMAC.exe` and press the debug button."
After "CMake generation finished.",
![image](https://github.com/afwbkbc/glsmac/assets/10828324/f6f10596-f8ec-4e28-ad1b-ed5a55202240)
I try build exe
![image](https://github.com/afwbkbc/glsmac/assets/10828324/12810225-8b78-4752-ad97-bce773497352)
but in process, i have a many errors (attached output)
[output_build.txt](https://github.com/afwbkbc/glsmac/files/13888410/output_build.txt)

Then i have window
![image](https://github.com/afwbkbc/glsmac/assets/10828324/cfc9d850-94b6-4648-b60b-8cedcd727ee7)
and open json
![image](https://github.com/afwbkbc/glsmac/assets/10828324/1c6db35c-63da-4c80-8f0f-cc65608fb891)

So, what i do wrong?

Thx

**Comment by afwbkbc** [comment]
Compiling with MSVC (default VS compiler) is not supported and won't be supported.
You need to install Clang component in Visual Studio installation and make sure it is used for building.
Check 'Visual Studio' section in compilation instructions in README.
I'll focus more on windows builds after v0.4, meaning better documentation and maybe some scripts, also gitlab ci that will build windows binaries so most people won't have to do it manually.
